services:     
    dakinquelia.groupdisplaytopic.listener:
        class: dakinquelia\groupdisplaytopic\event\listener
        arguments:
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }